// Generated C++ code from Pascal-like algorithm: Ex12_GradeManagementSystem
// Original algorithm: Ex12_GradeManagementSystem

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
std::string student1 = "";
std::string student2 = "";
std::string student3 = "";
int grade1 = 0;
int grade2 = 0;
int grade3 = 0;
int score1 = 0;
int score2 = 0;
int score3 = 0;
double avgGrade = 0;
double avgScore = 0;
int i = 0;
int choice = 0;
std::string searchName = "";
bool found = false;

double calculateAverageScore(int s1, int s2, int s3);
double calculateAverageGrade(int g1, int g2, int g3);
std::string getLetterGrade(int score);
void addStudent(std::string& name, int& grade, int& score, int studentNum);
void printStudentInfo(std::string name, int grade, int score);
void printClassSummary();
void findStudent(std::string search);
void sortStudents();

int main() {
    student1 = "";
    student2 = "";
    student3 = "";
    grade1 = 0;
    grade2 = 0;
    grade3 = 0;
    score1 = 0;
    score2 = 0;
    score3 = 0;
    choice = 0;
    while (choice != 7) {
        cout << "" << endl;
        cout << "===== STUDENT GRADE MANAGEMENT SYSTEM =====" << endl;
        cout << "1. Add Student 1" << endl;
        cout << "2. Add Student 2" << endl;
        cout << "3. Add Student 3" << endl;
        cout << "4. View All Students" << endl;
        cout << "5. Find Student" << endl;
        cout << "6. Sort Students by Score" << endl;
        cout << "7. Exit" << endl;
        cout << "==========================================" << endl;
        cout << "Enter your choice:" << endl;
        cin >> choice;
        if (choice == 1) {
            addStudent(student1, grade1, score1, 1);
        } else {
            if (choice == 2) {
                addStudent(student2, grade2, score2, 2);
            } else {
                if (choice == 3) {
                    addStudent(student3, grade3, score3, 3);
                } else {
                    if (choice == 4) {
                        cout << "===== ALL STUDENTS =====" << endl;
                        if (student1 != "") {
                            printStudentInfo(student1, grade1, score1);
                        }
                        if (student2 != "") {
                            printStudentInfo(student2, grade2, score2);
                        }
                        if (student3 != "") {
                            printStudentInfo(student3, grade3, score3);
                        }
                        if (((student1 != "") && (student2 != "")) && (student3 != "")) {
                            avgScore = calculateAverageScore(score1, score2, score3);
                            avgGrade = calculateAverageGrade(grade1, grade2, grade3);
                            printClassSummary();
                        } else {
                            cout << "Not all students have been added yet!" << endl;
                        }
                    } else {
                        if (choice == 5) {
                            cout << "Enter student name to search:" << endl;
                            cin >> searchName;
                            findStudent(searchName);
                        } else {
                            if (choice == 6) {
                                if (((student1 != "") && (student2 != "")) && (student3 != "")) {
                                    sortStudents();
                                } else {
                                    cout << "Need all 3 students to sort!" << endl;
                                }
                            } else {
                                if (choice == 7) {
                                    cout << "Thank you for using the Grade Management System!" << endl;
                                } else {
                                    cout << "Invalid choice! Please try again." << endl;
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    return 0;
}

double calculateAverageScore(int s1, int s2, int s3) {
    // Variable declarations
    int sum;

    sum = (s1 + s2) + s3;
    return sum / 3.0;
}

double calculateAverageGrade(int g1, int g2, int g3) {
    // Variable declarations
    int sum;

    sum = (g1 + g2) + g3;
    return sum / 3.0;
}

std::string getLetterGrade(int score) {
    if (score >= 90) {
        return "A";
    } else {
        if (score >= 80) {
            return "B";
        } else {
            if (score >= 70) {
                return "C";
            } else {
                if (score >= 60) {
                    return "D";
                } else {
                    return "F";
                }
            }
        }
    }
}

void addStudent(std::string& name, int& grade, int& score, int studentNum) {
    cout << "Enter name for student " << endl;
    cout << studentNum << endl;
    cout << ":" << endl;
    cin >> name;
    cout << "Enter grade (1-12) for " << endl;
    cout << name << endl;
    cout << ":" << endl;
    cin >> grade;
    cout << "Enter test score (0-100) for " << endl;
    cout << name << endl;
    cout << ":" << endl;
    cin >> score;
    cout << "Student added successfully!" << endl;
}

void printStudentInfo(std::string name, int grade, int score) {
    // Variable declarations
    std::string letterGrade;

    cout << "---------------------" << endl;
    cout << "Name: " << endl;
    cout << name << endl;
    cout << "Grade: " << endl;
    cout << grade << endl;
    cout << "Score: " << endl;
    cout << score << endl;
    letterGrade = getLetterGrade(score);
    cout << "Letter Grade: " << endl;
    cout << letterGrade << endl;
    cout << "---------------------" << endl;
}

void printClassSummary() {
    cout << "===== CLASS SUMMARY =====" << endl;
    cout << "Total Students: 3" << endl;
    cout << "Average Score: " << endl;
    cout << avgScore << endl;
    cout << "Average Grade Level: " << endl;
    cout << avgGrade << endl;
    cout << "========================" << endl;
}

void findStudent(std::string search) {
    found = false;
    if (student1 == search) {
        printStudentInfo(student1, grade1, score1);
        found = true;
    }
    if (student2 == search) {
        printStudentInfo(student2, grade2, score2);
        found = true;
    }
    if (student3 == search) {
        printStudentInfo(student3, grade3, score3);
        found = true;
    }
    if (!(found)) {
        cout << "Student not found: " << endl;
        cout << search << endl;
    }
}

void sortStudents() {
    // Variable declarations
    std::string tempName;
    int tempGrade, tempScore;

    if (score1 < score2) {
        tempName = student1;
        tempGrade = grade1;
        tempScore = score1;
        student1 = student2;
        grade1 = grade2;
        score1 = score2;
        student2 = tempName;
        grade2 = tempGrade;
        score2 = tempScore;
    }
    if (score1 < score3) {
        tempName = student1;
        tempGrade = grade1;
        tempScore = score1;
        student1 = student3;
        grade1 = grade3;
        score1 = score3;
        student3 = tempName;
        grade3 = tempGrade;
        score3 = tempScore;
    }
    if (score2 < score3) {
        tempName = student2;
        tempGrade = grade2;
        tempScore = score2;
        student2 = student3;
        grade2 = grade3;
        score2 = score3;
        student3 = tempName;
        grade3 = tempGrade;
        score3 = tempScore;
    }
    cout << "Students sorted by score (highest to lowest)!" << endl;
}

