// Generated C++ code from MyAlgo algorithm: Calculator
// Original algorithm: Calculator

// Generated by MyAlgo Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

int main() {
    // Variable declarations
    int num1, num2;
    int operation;
    int answer;

    cout << "Simple Calculator" << endl;
    cout << "1. Addition" << endl;
    cout << "2. Subtraction" << endl;
    cout << "3. Multiplication" << endl;
    cout << "4. Division" << endl;
    cout << "Enter choice (1-4): " << endl;
    cin >> operation;
    cout << "Enter first number: " << endl;
    cin >> num1;
    cout << "Enter second number: " << endl;
    cin >> num2;
    if ((operation == 1)) {
        answer = (num1 + num2);
        cout << "Result: " << endl;
        cout << answer << endl;
    }
    if ((operation == 2)) {
        answer = (num1 - num2);
        cout << "Result: " << endl;
        cout << answer << endl;
    }
    if ((operation == 3)) {
        answer = (num1 * num2);
        cout << "Result: " << endl;
        cout << answer << endl;
    }
    if ((operation == 4)) {
        if ((num2 != 0)) {
            answer = (num1 / num2);
            cout << "Result: " << endl;
            cout << answer << endl;
        } else {
            cout << "Error: Division by zero!" << endl;
        }
    }

    return 0;
}
