// Generated C++ code from Pascal-like algorithm: TestArrays
// Original algorithm: TestArrays

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int numbers[5];
int i = 0;
int sum = 0;

int main() {
    numbers[0] = 10;
    numbers[1] = 20;
    numbers[2] = 30;
    numbers[3] = 40;
    numbers[4] = 50;
    sum = 0;
    for (int i = 0; i <= 4; i++) {
        sum = sum + numbers[i];
    }
    cout << "Array elements:" << endl;
    for (int i = 0; i <= 4; i++) {
        cout << numbers[i] << endl;
    }
    cout << "Sum of array:" << endl;
    cout << sum << endl;

    return 0;
}

