// Generated C++ code from Pascal-like algorithm: Ex11_BankingSystem
// Original algorithm: Ex11_BankingSystem

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
double account1 = 0;
double account2 = 0;
std::string acc1Name = "";
std::string acc2Name = "";
int choice = 0;
double amount = 0;

void createAccount(std::string& name, double& balance);
void deposit(double& balance, double amount);
void withdraw(double& balance, double amount);
void transfer(double& fromBalance, double& toBalance, double amount, std::string fromName, std::string toName);
void printBalance(std::string name, double balance);
void printMenu();

int main() {
    account1 = 0.0;
    account2 = 0.0;
    acc1Name = "";
    acc2Name = "";
    choice = 0;
    while (choice != 10) {
        printMenu();
        cout << "Enter your choice:" << endl;
        cin >> choice;
        if (choice == 1) {
            createAccount(acc1Name, account1);
        } else {
            if (choice == 2) {
                createAccount(acc2Name, account2);
            } else {
                if (choice == 3) {
                    if (acc1Name != "") {
                        cout << "Enter deposit amount:" << endl;
                        cin >> amount;
                        deposit(account1, amount);
                    } else {
                        cout << "Account 1 not created yet!" << endl;
                    }
                } else {
                    if (choice == 4) {
                        if (acc2Name != "") {
                            cout << "Enter deposit amount:" << endl;
                            cin >> amount;
                            deposit(account2, amount);
                        } else {
                            cout << "Account 2 not created yet!" << endl;
                        }
                    } else {
                        if (choice == 5) {
                            if (acc1Name != "") {
                                cout << "Enter withdrawal amount:" << endl;
                                cin >> amount;
                                withdraw(account1, amount);
                            } else {
                                cout << "Account 1 not created yet!" << endl;
                            }
                        } else {
                            if (choice == 6) {
                                if (acc2Name != "") {
                                    cout << "Enter withdrawal amount:" << endl;
                                    cin >> amount;
                                    withdraw(account2, amount);
                                } else {
                                    cout << "Account 2 not created yet!" << endl;
                                }
                            } else {
                                if (choice == 7) {
                                    if ((acc1Name != "") && (acc2Name != "")) {
                                        cout << "Enter transfer amount:" << endl;
                                        cin >> amount;
                                        transfer(account1, account2, amount, acc1Name, acc2Name);
                                    } else {
                                        cout << "Both accounts must be created first!" << endl;
                                    }
                                } else {
                                    if (choice == 8) {
                                        if ((acc1Name != "") && (acc2Name != "")) {
                                            cout << "Enter transfer amount:" << endl;
                                            cin >> amount;
                                            transfer(account2, account1, amount, acc2Name, acc1Name);
                                        } else {
                                            cout << "Both accounts must be created first!" << endl;
                                        }
                                    } else {
                                        if (choice == 9) {
                                            cout << "===== CURRENT BALANCES =====" << endl;
                                            if (acc1Name != "") {
                                                printBalance(acc1Name, account1);
                                            } else {
                                                cout << "Account 1: Not created" << endl;
                                            }
                                            if (acc2Name != "") {
                                                printBalance(acc2Name, account2);
                                            } else {
                                                cout << "Account 2: Not created" << endl;
                                            }
                                            cout << "============================" << endl;
                                        } else {
                                            if (choice == 10) {
                                                cout << "Thank you for using our banking system!" << endl;
                                            } else {
                                                cout << "Invalid choice! Please try again." << endl;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    return 0;
}

void createAccount(std::string& name, double& balance) {
    cout << "Enter account holder name:" << endl;
    cin >> name;
    balance = 0.0;
    cout << "Account created for " << endl;
    cout << name << endl;
    cout << " with initial balance 0.0" << endl;
}

void deposit(double& balance, double amount) {
    if (amount > 0) {
        balance = balance + amount;
        cout << "Deposited: " << endl;
        cout << amount << endl;
        cout << "New balance: " << endl;
        cout << balance << endl;
    } else {
        cout << "Invalid deposit amount!" << endl;
    }
}

void withdraw(double& balance, double amount) {
    if (amount <= 0) {
        cout << "Invalid withdrawal amount!" << endl;
    } else {
        if (amount <= balance) {
            balance = balance - amount;
            cout << "Withdrawn: " << endl;
            cout << amount << endl;
            cout << "New balance: " << endl;
            cout << balance << endl;
        } else {
            cout << "Insufficient funds!" << endl;
            cout << "Current balance: " << endl;
            cout << balance << endl;
        }
    }
}

void transfer(double& fromBalance, double& toBalance, double amount, std::string fromName, std::string toName) {
    if (amount <= 0) {
        cout << "Invalid transfer amount!" << endl;
    } else {
        if (amount <= fromBalance) {
            fromBalance = fromBalance - amount;
            toBalance = toBalance + amount;
            cout << "Transferred: " << endl;
            cout << amount << endl;
            cout << "From: " << endl;
            cout << fromName << endl;
            cout << "To: " << endl;
            cout << toName << endl;
            cout << fromName << endl;
            cout << " new balance: " << endl;
            cout << fromBalance << endl;
            cout << toName << endl;
            cout << " new balance: " << endl;
            cout << toBalance << endl;
        } else {
            cout << "Insufficient funds for transfer!" << endl;
            cout << fromName << endl;
            cout << " balance: " << endl;
            cout << fromBalance << endl;
        }
    }
}

void printBalance(std::string name, double balance) {
    cout << "Account: " << endl;
    cout << name << endl;
    cout << "Balance: $" << endl;
    cout << balance << endl;
}

void printMenu() {
    cout << "===== BANKING SYSTEM =====" << endl;
    cout << "1. Create Account 1" << endl;
    cout << "2. Create Account 2" << endl;
    cout << "3. Deposit to Account 1" << endl;
    cout << "4. Deposit to Account 2" << endl;
    cout << "5. Withdraw from Account 1" << endl;
    cout << "6. Withdraw from Account 2" << endl;
    cout << "7. Transfer Account 1 -> Account 2" << endl;
    cout << "8. Transfer Account 2 -> Account 1" << endl;
    cout << "9. View Balances" << endl;
    cout << "10. Exit" << endl;
    cout << "===========================" << endl;
}

