#ifndef CODEGENERATOR_HPP
#define CODEGENERATOR_HPP

#include "AST.hpp"
#include "SymbolTable.hpp"
#include <iostream>
#include <fstream>
#include <string>
#include <memory>
#include <vector>
#include <map>

class CodeGenerator {
private:
    std::shared_ptr<ASTNode> ast;
    std::ofstream outputFile;
    std::string outputFilename;
    int indentLevel;
    bool generateMain;
    
    std::string indent() const {
        return std::string(indentLevel * 4, ' ');
    }
    
    std::string cppType(const std::string& typeName) {
        if (typeName == "integer") return "int";
        if (typeName == "real") return "double";
        if (typeName == "boolean") return "bool";
        if (typeName == "string") return "std::string";
        return sanitizeIdentifier(typeName);
    }
    
    std::string cppBool(bool value) {
        return value ? "true" : "false";
    }
    
    std::string sanitizeIdentifier(const std::string& name) {
        // In C++, we can use the same identifiers as in Pascal
        // But we need to avoid C++ keywords
        static std::map<std::string, bool> cppKeywords = {
            {"alignas", true}, {"alignof", true}, {"and", true}, {"and_eq", true},
            {"asm", true}, {"auto", true}, {"bitand", true}, {"bitor", true},
            {"bool", true}, {"break", true}, {"case", true}, {"catch", true},
            {"char", true}, {"char8_t", true}, {"char16_t", true}, {"char32_t", true},
            {"class", true}, {"compl", true}, {"concept", true}, {"const", true},
            {"consteval", true}, {"constexpr", true}, {"const_cast", true},
            {"continue", true}, {"co_await", true}, {"co_return", true}, {"co_yield", true},
            {"decltype", true}, {"default", true}, {"delete", true}, {"do", true},
            {"double", true}, {"dynamic_cast", true}, {"else", true}, {"enum", true},
            {"explicit", true}, {"export", true}, {"extern", true}, {"false", true},
            {"float", true}, {"for", true}, {"friend", true}, {"goto", true},
            {"if", true}, {"inline", true}, {"int", true}, {"long", true},
            {"mutable", true}, {"namespace", true}, {"new", true}, {"noexcept", true},
            {"not", true}, {"not_eq", true}, {"nullptr", true}, {"operator", true},
            {"or", true}, {"or_eq", true}, {"private", true}, {"protected", true},
            {"public", true}, {"register", true}, {"reinterpret_cast", true},
            {"requires", true}, {"return", true}, {"short", true}, {"signed", true},
            {"sizeof", true}, {"static", true}, {"static_assert", true},
            {"static_cast", true}, {"struct", true}, {"switch", true}, {"template", true},
            {"this", true}, {"thread_local", true}, {"throw", true}, {"true", true},
            {"try", true}, {"typedef", true}, {"typeid", true}, {"typename", true},
            {"union", true}, {"unsigned", true}, {"using", true}, {"virtual", true},
            {"void", true}, {"volatile", true}, {"wchar_t", true}, {"while", true},
            {"xor", true}, {"xor_eq", true}
        };
        
        if (cppKeywords.find(name) != cppKeywords.end()) {
            return name + "_"; // Append underscore to avoid keyword conflict
        }
        return name;
    }

    std::string sanitizeIdentifierPath(const std::string& path) {
        std::string result;
        std::string currentPart;

        for (char ch : path) {
            if (ch == '.') {
                if (!currentPart.empty()) {
                    if (!result.empty()) result += ".";
                    result += sanitizeIdentifier(currentPart);
                    currentPart.clear();
                }
            } else {
                currentPart += ch;
            }
        }

        if (!currentPart.empty()) {
            if (!result.empty()) result += ".";
            result += sanitizeIdentifier(currentPart);
        }

        return result;
    }
    
    void generateIncludes() {
        outputFile << "// Generated by Pascal-like to C++ Compiler\n";
        outputFile << "// DO NOT EDIT THIS FILE DIRECTLY\n\n";
        outputFile << "#include <iostream>\n";
        outputFile << "#include <cmath>\n"; // For math operations
        outputFile << "#include <string>\n"; // For string support
        outputFile << "using namespace std;\n\n";
    }
    
    void generateExpression(const std::shared_ptr<ExpressionNode>& expr, bool needParens = false) {
        if (!expr) return;
        
        if (auto num = std::dynamic_pointer_cast<NumberNode>(expr)) {
            outputFile << num->value;
        }
        else if (auto str = std::dynamic_pointer_cast<StringNode>(expr)) {
            outputFile << "\"" << str->value << "\"";
        }
        else if (auto boolean = std::dynamic_pointer_cast<BooleanNode>(expr)) {
            outputFile << cppBool(boolean->value);
        }
        else if (auto var = std::dynamic_pointer_cast<VariableNode>(expr)) {
            outputFile << sanitizeIdentifierPath(var->name);
        }
        else if (auto binOp = std::dynamic_pointer_cast<BinaryOpNode>(expr)) {
            std::string op = binOp->op;
            
            if (op == "DIV") {
                if (needParens) outputFile << "(";
                generateExpression(binOp->left, true);
                outputFile << " / ";
                generateExpression(binOp->right, true);
                if (needParens) outputFile << ")";
            }
            else if (op == "MOD") {
                if (needParens) outputFile << "(";
                generateExpression(binOp->left, true);
                outputFile << " % ";
                generateExpression(binOp->right, true);
                if (needParens) outputFile << ")";
            }
            else if (op == "<>") {
                if (needParens) outputFile << "(";
                generateExpression(binOp->left, true);
                outputFile << " != ";
                generateExpression(binOp->right, true);
                if (needParens) outputFile << ")";
            }
            else if (op == "and") {
                if (needParens) outputFile << "(";
                generateExpression(binOp->left, true);
                outputFile << " && ";
                generateExpression(binOp->right, true);
                if (needParens) outputFile << ")";
            }
            else if (op == "or") {
                if (needParens) outputFile << "(";
                generateExpression(binOp->left, true);
                outputFile << " || ";
                generateExpression(binOp->right, true);
                if (needParens) outputFile << ")";
            }
            else if (op == "=") {
                if (needParens) outputFile << "(";
                generateExpression(binOp->left, true);
                outputFile << " == ";
                generateExpression(binOp->right, true);
                if (needParens) outputFile << ")";
            }
            else {
                if (needParens) outputFile << "(";
                generateExpression(binOp->left, true);
                outputFile << " " << op << " ";
                generateExpression(binOp->right, true);
                if (needParens) outputFile << ")";
            }
        }
        else if (auto unaryOp = std::dynamic_pointer_cast<UnaryOpNode>(expr)) {
            if (unaryOp->op == "not") {
                outputFile << "!(";
                generateExpression(unaryOp->operand);
                outputFile << ")";
            }
            else {
                outputFile << unaryOp->op;
                generateExpression(unaryOp->operand);
            }
        }
        else if (auto call = std::dynamic_pointer_cast<CallNode>(expr)) {
            outputFile << sanitizeIdentifier(call->functionName) << "(";
            for (size_t i = 0; i < call->arguments.size(); i++) {
                if (i > 0) outputFile << ", ";
                generateExpression(call->arguments[i]);
            }
            outputFile << ")";
        }
        else if (auto arrayAccess = std::dynamic_pointer_cast<ArrayAccessNode>(expr)) {
            outputFile << sanitizeIdentifierPath(arrayAccess->arrayName) << "[";
            generateExpression(arrayAccess->index);
            outputFile << "]";

            if (arrayAccess->secondIndex) {
                outputFile << "[";
                generateExpression(arrayAccess->secondIndex);
                outputFile << "]";
            }
        }
    }
    
    void generateStatement(const std::shared_ptr<StatementNode>& stmt) {
        if (!stmt) return;
        
        if (auto assign = std::dynamic_pointer_cast<AssignmentNode>(stmt)) {
            outputFile << indent() << sanitizeIdentifierPath(assign->variableName);
            
            // Handle array indexing if present
            if (assign->arrayIndex) {
                outputFile << "[";
                generateExpression(assign->arrayIndex);
                outputFile << "]";

                if (assign->matrixIndex) {
                    outputFile << "[";
                    generateExpression(assign->matrixIndex);
                    outputFile << "]";
                }
            }
            
            outputFile << " = ";
            generateExpression(assign->expression);
            outputFile << ";\n";
        }
        else if (auto returnStmt = std::dynamic_pointer_cast<ReturnStatementNode>(stmt)) {
            outputFile << indent() << "return";
            if (returnStmt->expression) {
                outputFile << " ";
                generateExpression(returnStmt->expression);
            }
            outputFile << ";\n";
        }
        else if (auto ifStmt = std::dynamic_pointer_cast<IfStatementNode>(stmt)) {
            outputFile << indent() << "if (";
            generateExpression(ifStmt->condition);
            outputFile << ") {\n";
            
            indentLevel++;
            generateBlock(ifStmt->thenBlock);
            indentLevel--;
            
            if (ifStmt->elseBlock && !ifStmt->elseBlock->statements.empty()) {
                outputFile << indent() << "} else {\n";
                indentLevel++;
                generateBlock(ifStmt->elseBlock);
                indentLevel--;
            }
            
            outputFile << indent() << "}\n";
        }
        else if (auto forStmt = std::dynamic_pointer_cast<ForStatementNode>(stmt)) {
            outputFile << indent() << "for (int " << sanitizeIdentifier(forStmt->variableName) << " = ";
            generateExpression(forStmt->startExpr);
            outputFile << "; " << sanitizeIdentifier(forStmt->variableName) << " <= ";
            generateExpression(forStmt->endExpr);
            outputFile << "; " << sanitizeIdentifier(forStmt->variableName) << "++) {\n";
            
            indentLevel++;
            generateBlock(forStmt->body);
            indentLevel--;
            
            outputFile << indent() << "}\n";
        }
        else if (auto whileStmt = std::dynamic_pointer_cast<WhileStatementNode>(stmt)) {
            outputFile << indent() << "while (";
            generateExpression(whileStmt->condition);
            outputFile << ") {\n";
            
            indentLevel++;
            generateBlock(whileStmt->body);
            indentLevel--;
            
            outputFile << indent() << "}\n";
        }
        else if (auto repeatStmt = std::dynamic_pointer_cast<RepeatStatementNode>(stmt)) {
            outputFile << indent() << "do {\n";
            
            indentLevel++;
            generateBlock(repeatStmt->body);
            indentLevel--;
            
            outputFile << indent() << "} while (!(";
            generateExpression(repeatStmt->condition);
            outputFile << "));\n";
        }
        else if (auto readStmt = std::dynamic_pointer_cast<ReadStatementNode>(stmt)) {
            outputFile << indent() << "cin >> " << sanitizeIdentifierPath(readStmt->variableName) << ";\n";
        }
        else if (auto writeStmt = std::dynamic_pointer_cast<WriteStatementNode>(stmt)) {
            outputFile << indent() << "cout << ";
            generateExpression(writeStmt->expression);
            outputFile << " << endl;\n";
        }
        else if (auto exprStmt = std::dynamic_pointer_cast<ExpressionStatementNode>(stmt)) {
            // Handle expression statements (like procedure calls)
            outputFile << indent();
            generateExpression(exprStmt->expression);
            outputFile << ";\n";
        }
        else if (auto call = std::dynamic_pointer_cast<CallNode>(std::dynamic_pointer_cast<ExpressionNode>(stmt))) {
            // Handle procedure calls as statements (procedure calls don't return values)
            outputFile << indent() << sanitizeIdentifier(call->functionName) << "(";
            for (size_t i = 0; i < call->arguments.size(); i++) {
                generateExpression(call->arguments[i]);
                if (i < call->arguments.size() - 1) {
                    outputFile << ", ";
                }
            }
            outputFile << ");\n";
        }
    }
    
    void generateBlock(const std::shared_ptr<BlockNode>& block) {
        if (!block) return;
        
        for (const auto& stmt : block->statements) {
            if (stmt) {
                generateStatement(stmt);
            }
        }
    }
    
    void generateVariableDeclarations(const std::vector<std::shared_ptr<VarDeclNode>>& variables) {
        if (variables.empty()) return;
        
        outputFile << indent() << "// Variable declarations\n";
        for (const auto& varDecl : variables) {
            std::string cppTypeStr = cppType(varDecl->typeName);
            
            outputFile << indent() << cppTypeStr << " ";
            for (size_t i = 0; i < varDecl->names.size(); i++) {
                if (i > 0) outputFile << ", ";
                outputFile << sanitizeIdentifier(varDecl->names[i]);
                
                // Add array brackets if this is an array
                if (varDecl->isArray) {
                    outputFile << "[" << varDecl->arraySize << "]";
                    if (varDecl->isMatrix) {
                        outputFile << "[" << varDecl->arrayColumns << "]";
                    }
                }
            }
            outputFile << ";\n";
        }
        outputFile << "\n";
    }
    
    void generateFunction(const std::shared_ptr<FunctionNode>& func) {
        std::string cppReturnType = cppType(func->returnType);
        
        outputFile << cppReturnType << " " << sanitizeIdentifier(func->name) << "(";
        
        // Generate parameters
        for (size_t i = 0; i < func->parameters.size(); i++) {
            if (i > 0) outputFile << ", ";
            const auto& param = func->parameters[i];
            std::string paramType = cppType(param->typeName);
            
            if (param->isReference) {
                paramType += "&";  // Pass by reference
            }
            
            outputFile << paramType << " " << sanitizeIdentifier(param->name);
        }
        
        outputFile << ") {\n";
        indentLevel++;
        
        // Generate local variables
        generateVariableDeclarations(func->variables);
        
        // Generate function body
        generateBlock(func->body);
        
        // Add default return if missing for non-void functions
        bool hasReturn = false;
        if (func->body) {
            for (const auto& stmt : func->body->statements) {
                if (auto returnStmt = std::dynamic_pointer_cast<ReturnStatementNode>(stmt)) {
                    hasReturn = true;
                    break;
                }
            }
        }
        
        if (!hasReturn) {
            if (func->returnType == "integer") {
                outputFile << indent() << "return 0;\n";
            } else if (func->returnType == "real") {
                outputFile << indent() << "return 0.0;\n";
            } else if (func->returnType == "boolean") {
                outputFile << indent() << "return false;\n";
            }
        }
        
        indentLevel--;
        outputFile << "}\n\n";
    }
    
    void generateProcedure(const std::shared_ptr<ProcedureNode>& proc) {
        outputFile << "void " << sanitizeIdentifier(proc->name) << "(";
        
        // Generate parameters
        for (size_t i = 0; i < proc->parameters.size(); i++) {
            if (i > 0) outputFile << ", ";
            const auto& param = proc->parameters[i];
            std::string paramType = cppType(param->typeName);
            
            if (param->isReference) {
                paramType += "&";  // Pass by reference
            }
            
            outputFile << paramType << " " << sanitizeIdentifier(param->name);
        }
        
        outputFile << ") {\n";
        indentLevel++;
        
        // Generate local variables
        generateVariableDeclarations(proc->variables);
        
        // Generate procedure body
        generateBlock(proc->body);
        
        indentLevel--;
        outputFile << "}\n\n";
    }
    
    void generateAlgorithm(const std::shared_ptr<AlgorithmNode>& algo) {
        outputFile << "// Generated C++ code from Pascal-like algorithm: " << algo->name << "\n";
        outputFile << "// Original algorithm: " << algo->name << "\n\n";
        
        generateIncludes();

        if (!algo->structures.empty()) {
            for (const auto& structure : algo->structures) {
                outputFile << "struct " << sanitizeIdentifier(structure->name) << " {\n";
                for (const auto& field : structure->fields) {
                    outputFile << "    " << cppType(field->typeName) << " "
                               << sanitizeIdentifier(field->name);
                    if (field->typeName == "string") {
                        outputFile << " = \"\"";
                    } else if (field->typeName == "boolean") {
                        outputFile << " = false";
                    } else {
                        outputFile << " = 0";
                    }
                    outputFile << ";\n";
                }
                outputFile << "};\n\n";
            }
        }
        
        // Generate global variable declarations FIRST (before all functions)
        if (!algo->variables.empty()) {
            outputFile << "// Global variables\n";
            for (const auto& varDecl : algo->variables) {
                std::string varType = cppType(varDecl->typeName);
                for (const auto& name : varDecl->names) {
                    outputFile << varType << " " << sanitizeIdentifier(name);
                    
                    // Add array brackets if this is an array
                    if (varDecl->isArray) {
                        outputFile << "[" << varDecl->arraySize << "]";
                        if (varDecl->isMatrix) {
                            outputFile << "[" << varDecl->arrayColumns << "]";
                        }
                    }
                    
                    if (varType == "std::string" && !varDecl->isArray) {
                        outputFile << " = \"\"";
                    } else if (varType == "bool" && !varDecl->isArray) {
                        outputFile << " = false";
                    } else if (!varDecl->isArray &&
                               (varType == "int" || varType == "double")) {
                        outputFile << " = 0";
                    }
                    outputFile << ";\n";
                }
            }
            outputFile << "\n";
        }
        
        // Generate forward declarations for functions
        for (const auto& func : algo->functions) {
            std::string cppReturnType = cppType(func->returnType);
            
            outputFile << cppReturnType << " " << sanitizeIdentifier(func->name) << "(";
            for (size_t i = 0; i < func->parameters.size(); i++) {
                if (i > 0) outputFile << ", ";
                const auto& param = func->parameters[i];
                std::string paramType = cppType(param->typeName);
                
                if (param->isReference) paramType += "&";
                outputFile << paramType << " " << sanitizeIdentifier(param->name);
            }
            outputFile << ");\n";
        }
        
        // Generate forward declarations for procedures
        for (const auto& proc : algo->procedures) {
            outputFile << "void " << sanitizeIdentifier(proc->name) << "(";
            for (size_t i = 0; i < proc->parameters.size(); i++) {
                if (i > 0) outputFile << ", ";
                const auto& param = proc->parameters[i];
                std::string paramType = cppType(param->typeName);
                
                if (param->isReference) paramType += "&";
                outputFile << paramType << " " << sanitizeIdentifier(param->name);
            }
            outputFile << ");\n";
        }
        
        if (!algo->functions.empty() || !algo->procedures.empty()) {
            outputFile << "\n";
        }
        
        if (generateMain) {
            outputFile << "int main() {\n";
            indentLevel++;
        }
        
        // Don't generate variable declarations here - they're now global
        
        // Generate statements
        generateBlock(algo->body);
        
        if (generateMain) {
            outputFile << "\n" << indent() << "return 0;\n";
            indentLevel--;
            outputFile << "}\n\n";
        }
        
        // Generate function and procedure implementations after main
        for (const auto& func : algo->functions) {
            generateFunction(func);
        }
        
        for (const auto& proc : algo->procedures) {
            generateProcedure(proc);
        }
    }
    
public:
    CodeGenerator(const std::shared_ptr<ASTNode>& ast, 
                  const std::string& outputFilename = "output.cpp",
                  bool generateMain = true)
        : ast(ast), outputFilename(outputFilename), 
          indentLevel(0), generateMain(generateMain) {}
    
    bool generate() {
        outputFile.open(outputFilename);
        if (!outputFile.is_open()) {
            std::cerr << "Error: Could not open output file " << outputFilename << std::endl;
            return false;
        }
        
        try {
            if (auto algo = std::dynamic_pointer_cast<AlgorithmNode>(ast)) {
                generateAlgorithm(algo);
            } else {
                std::cerr << "Error: AST root is not an AlgorithmNode" << std::endl;
                return false;
            }
            
            outputFile.close();
            //std::cout << "C++ code generated successfully: " << outputFilename << std::endl;
            return true;
        }
        catch (const std::exception& e) {
            std::cerr << "Error during code generation: " << e.what() << std::endl;
            outputFile.close();
            return false;
        }
    }
    
    std::string getOutputFilename() const {
        return outputFilename;
    }
};

#endif